name: DynamicPVPArena
version: '${version}'
depend:
  - WorldGuard
  - WGRegionEvents
main: com.github.kacperleague9.hubpvp.HubPVP
api-version: 1.13
commands:
  dynamicpvparena:
    aliases:
      - dpa
      - hubpvp
    permission: dynamicpvparena.command
